// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwBkXayXOWDHJozgGCDjpOClZouMEBCMg',
    appId: '1:894760344850:web:13069014f9974788e0e7cb',
    messagingSenderId: '894760344850',
    projectId: 'mytodo-app-3e540',
    authDomain: 'mytodo-app-3e540.firebaseapp.com',
    storageBucket: 'mytodo-app-3e540.appspot.com',
    measurementId: 'G-KQWQV6GJ39',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCL_7GFg0Q7y8muabTtKsSTMJA5JEzmO98',
    appId: '1:894760344850:android:386c1811ab13727de0e7cb',
    messagingSenderId: '894760344850',
    projectId: 'mytodo-app-3e540',
    storageBucket: 'mytodo-app-3e540.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApime4T6Vx4Dp6qgWIrc-PjsdUQF_Nc1I',
    appId: '1:894760344850:ios:a4bbeba799db1a05e0e7cb',
    messagingSenderId: '894760344850',
    projectId: 'mytodo-app-3e540',
    storageBucket: 'mytodo-app-3e540.appspot.com',
    iosClientId: '894760344850-qaf9fff3m8t7pbmrisglrdogcu1tdcbe.apps.googleusercontent.com',
    iosBundleId: 'com.example.mytodoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApime4T6Vx4Dp6qgWIrc-PjsdUQF_Nc1I',
    appId: '1:894760344850:ios:a4bbeba799db1a05e0e7cb',
    messagingSenderId: '894760344850',
    projectId: 'mytodo-app-3e540',
    storageBucket: 'mytodo-app-3e540.appspot.com',
    iosClientId: '894760344850-qaf9fff3m8t7pbmrisglrdogcu1tdcbe.apps.googleusercontent.com',
    iosBundleId: 'com.example.mytodoApp',
  );
}
